apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-sample
  template:
    metadata:
      labels:
        app: cicd-sample
    spec:
      containers:
      - name: web
        image: <adi119>/jenkins-ci-cd-sample:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-sample
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: cicd-sample
